import { Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";

const georgian = Noto_Sans_Georgian({ subsets: ["georgian"]})

export const metadata = {
  title: "unOfficial Lego",
  description: "Generated by create next app",
};

const locales = ['en', 'ka'];
export function generateStaticParams() {
  return locales.map((locale) => ({locale}))
}

export default function RootLayout({ children, params: {locale} }) {
  return (
    <html lang={locale} >
      <body className={georgian.className}>{children}</body>
    </html>
  );
}
