import "./globals.css";
import { NextIntlClientProvider } from 'next-intl';
import { unstable_setRequestLocale } from 'next-intl/server';

export const metadata = {
  title: "unOfficial Lego",
  description: "Generated by create next app",
};

const locales = ['en', 'ka'];
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }))
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  unstable_setRequestLocale(locale);
  return (
    <html lang={locale} >
      <body>
        <NextIntlClientProvider
          locale={locale}
        >
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic"
